const SUPABASE_URL = 'https://caupwgbtiuzildiejcuh.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdXB3Z2J0aXV6aWxkaWVqY3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNzAyNjMsImV4cCI6MjA3OTY0NjI2M30.ysnwVJPGcdvkKZvkQCBsoKUHXna1LVpF016LAOcfdYw';
