-- Create accounts table
create table if not exists accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null,
  password text not null -- Note: In a real production app, encrypt this!
);

-- Create attendance_logs table
create table if not exists attendance_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null,
  qr_code text not null,
  status text not null,
  message text
);

-- Enable Row Level Security (RLS)
alter table accounts enable row level security;
alter table attendance_logs enable row level security;

-- Create policies (allow all for authenticated users for now)
create policy "Enable all access for authenticated users" on accounts
  for all using (auth.role() = 'authenticated');

create policy "Enable all access for authenticated users" on attendance_logs
  for all using (auth.role() = 'authenticated');
